#!/bin/sh

if [ -L "$0" ]
then
  SCRIPTSETUP="$(readlink "$0")"
else
  SCRIPTSETUP="$0"
fi

DOTFILESDIRREL=$(dirname $SCRIPTSETUP)
cd $DOTFILESDIRREL/..
DOTFILESDIR=$(pwd -P)

[ $(uname -s) = "Darwin" ] && export MACOS=1 && export UNIX=1
[ $(uname -s) = "Linux" ] && export LINUX=1 && export UNIX=1

if [ $MACOS ]
then
  export VSCODE="$HOME/Library/Application Support/Code/User"
elif [ $LINUX ]
then
  export VSCODE="$HOME/.config/Code/User"
fi

for DOTFILE in *; do
  if [ -d $DOTFILE ] && [ -f "$DOTFILE/.stowrc" ]
  then
      pushd $DOTFILE
      stow .
      popd
  else
      echo "nothing to stow in $DOTFILE"
  fi
done
