#!/bin/sh
# Run by Strap after installing Brewfile dependencies
#
echo "Enable keyboard key reapeat"
defaults write -g ApplePressAndHoldEnabled -bool false

# Enable authorizing sudo using TouchID
echo "Enable authorizing sudo using TouchID"
setup/macos/touchid-enable-pam-sudo

echo "Installing VS Code extensions"
vscode/install-vscode-extensions
