import = ["/Users/benshu/.config/alacritty/dracula.toml"]
startup_mode = "Windowed"

[debug]
log_level = "info"
persistent_logging = true

[env]
TERM = "alacritty-direct"

[font]
scale_with_dpi = true
size = 14.0
use_thin_strokes = true

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[window]
decorations = "Full"

[window.class]
general = "Alacritty"
instance = "Alacritty"
